### PR TITLE
Trying to update my git

### PR DESCRIPTION
**Pull request by cghaase**

### CODE REVIEW

**Comment by cReedHranac** [comment]
Hey why did you close the Pull request? Does that mean you don't want me to
do it?
-R$

On Wed, Aug 9, 2017 at 7:54 AM, Catherine G. Haase <notifications@github.com

**Comment by cghaase** [comment]
Was it a pull request that I did or you? I was trying to update my master
and did a pull request the wrong way so I closed it. Did you do one too or
are you talking about the one I did? I've been using the Git integration in
RStudio and was just checking things out on the website and confused
myself...again.

Katie Haase, PhD
Postdoctoral Researcher
Department of Microbiology & Immunology
Montana State University
Email: catherine.haase@montana.edu
Website: catherineghaase.weebly.com
Ph: (201) 230-6346

"If you look at the science about what is happening on earth and aren't
pessimistic, you don't understand the data. But if you meet the people who
are working to restore this earth and the lives of the poor, and you aren't
optimistic, you haven't got a pulse." - Paul Hawken

On Tue, Aug 8, 2017 at 4:23 PM, Carter Reed Hranac <notifications@github.com

**Comment by cReedHranac** [comment]
haha I don't think that I'd opened any. The git ingratiation tools through
studio can be a bit lacking. Try the git powershell, that'll make it seem
like bash and you'll be much easier to google your way through problems.

All the changes you want me to bring in are on your master?
-R$

**Comment by cghaase** [comment]
I think so, I just updated the cooling equation and fixed the fat
conversion factor. Everything else I've been working with is in my separate
branch.

Katie Haase, PhD
Postdoctoral Researcher
Department of Microbiology & Immunology
Montana State University
Email: catherine.haase@montana.edu
Website: catherineghaase.weebly.com
Ph: (201) 230-6346

"If you look at the science about what is happening on earth and aren't
pessimistic, you don't understand the data. But if you meet the people who
are working to restore this earth and the lives of the poor, and you aren't
optimistic, you haven't got a pulse." - Paul Hawken

On Tue, Aug 8, 2017 at 4:37 PM, Carter Reed Hranac <notifications@github.com
> wrote:

> haha I don't think that I'd opened any. The git ingratiation tools through
> studio can be a bit lacking. Try the git powershell, that'll make it seem
> like bash and you'll be much easier to google your way through problems.
>
> All the changes you want me to bring in are on your master?
> -R$
>
> On Wed, Aug 9, 2017 at 10:30 AM, Catherine G. Haase <
>

**Comment by cReedHranac** [comment]
okay, do you want me to take a look at any of those or are they still under
R&D?

**Comment by cReedHranac** [comment]
Also, I only see the cooling equation in the files changed. I don't see any changes in the fat conversion function.

UPDATE: idk why it wasn't highlighted when I looked at the 'files changed' above but I got it when I merged your master into my testing branch. Dave and I have a meeting today to check out your findings and I'll let you know the outcome of that. 
 -R

**Comment by cghaase** [comment]
Hum, weird? I see there are changes in my master...not sure why they are
not coming up.

Katie Haase, PhD
Postdoctoral Researcher
Department of Microbiology & Immunology
Montana State University
Email: catherine.haase@montana.edu
Website: catherineghaase.weebly.com
Ph: (201) 230-6346

"If you look at the science about what is happening on earth and aren't
pessimistic, you don't understand the data. But if you meet the people who
are working to restore this earth and the lives of the poor, and you aren't
optimistic, you haven't got a pulse." - Paul Hawken

On Tue, Aug 8, 2017 at 4:51 PM, Carter Reed Hranac <notifications@github.com

**Pull request closed without merging**
